// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUfahqLIPRFjI0Tr31wmGuen9WpdfQoiY',
    appId: '1:825720519411:web:cc7499e01adadb03ef1586',
    messagingSenderId: '825720519411',
    projectId: 'minecraft-minigames',
    authDomain: 'minecraft-minigames.firebaseapp.com',
    storageBucket: 'minecraft-minigames.firebasestorage.app',
    measurementId: 'G-MD3RZEXE4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEsp8zwjgb3Txem90_R5qLwYyqLmsA20k',
    appId: '1:825720519411:android:0ab9aea897c5e301ef1586',
    messagingSenderId: '825720519411',
    projectId: 'minecraft-minigames',
    storageBucket: 'minecraft-minigames.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGTS5hmXVoqkKRdg9jHTJ-irXFV2IJIIM',
    appId: '1:825720519411:ios:5017907edc4d1f96ef1586',
    messagingSenderId: '825720519411',
    projectId: 'minecraft-minigames',
    storageBucket: 'minecraft-minigames.firebasestorage.app',
    iosBundleId: 'com.ed.minigamesMinecraft',
  );
}
